**[NUMPY BASICS

CREATING A NUMPY ARRAY & ITA ATTRIBUTES

In [ ]:
#importing numpy library
import numpy as np
my_list=[1,2,3,4,5]  #creating a list
 #changung the list into a numpy array
my_array=np.array(my_list)
 #printing the array
print(my_array)


 #creating a 0-D numpy array
zero_array=np.array(42)

 #printing the )_D numpy array
print(zero_array)

 #intested of creating a list on a seperated variable we csn directly pass the list to.array() function like this.
my_array=np.array([1,2,3,4,5])
 #printing the 1-D
print(my_array)


 #lets create a 2-D array
two_d_array=np.array([[1,2,3],[4,5,6]])
 #printing the 2-D np.array
print(two_d_array)

 #lets create a 3-D array
three_d_array=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
 #printing 3d array
print(three_d_array)


[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


**an array and see its atributes**

In [ ]:
#lets create an array and see its atributes
my_array=np.array([[1,2,3],[4,5,6]])
print(my_array) #printing the array
print(my_array.ndim) #printing the dimension of the array
print(my_array.shape) #printing the shape of the array
print(my_array.dtype) #printing the type of the array
print(my_array.size) #printing the size of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


#**accesing and manupulation array elements**

In [ ]:
#lets create a 1-D array annd print one of its elements
one_arr=np.array([1,2,3,4,5,6])
print(one_arr[4])

      #lets print using negetive index
print(one_arr[-3])


5
4


#lets do for 2D aray


In [ ]:
#lets do for 2D aray
two_arr=np.array([[1,2,3],[4,5,6]])
print(two_arr[1,2])
print(two_arr[0,-1])

6
3


In [ ]:
##lets do for 3-D aray
three_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])

print(three_arr[1,0,0])#bracket

12
7


In [ ]:
#lets do for 3-D negetive aray
three_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[-1,-1,-2])

11


**SLICING**

In [ ]:
#some important slicing concepts
array[start:end]
array[stat:end:steps]



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#slicing array from 0th index to 8th index
my_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])
print(my_array[0:6])

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6]


In [ ]:
#slicing with the steps
my_new_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])  #2=steps ,
print(my_new_array[0:9:3])  #3 steps counting

[1 3 5 7 9]
[1 4 7]


In [ ]:
#slicing on a 2-D array
my_two_d =np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])

print(my_two_d[0,2:6])

[10 11 12 13 14 15]
[3 4 5 6]


NUMPY ARRAY

In [ ]:
#create a numpy array from the list [7,14,21,28] .print the array.

array=[7,14,21,28]
print(array)

[7, 14, 21, 28]


In [ ]:
my_two_d
my_two_d=np.array([[5,10,15],[20,25,30]])  #print the shape and number of dimension
print(my_two_d.shape)
print(my_two_d.ndim)



(2, 3)
2


In [ ]:
b=np.zeros((2,3))
print(b)
a=np.arange(0,12,3) #using np.arrage to create an aray
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
numpy_array=[2,4,6,8] #multiply by all element
print(numpy_array*3)



[2, 4, 6, 8, 2, 4, 6, 8, 2, 4, 6, 8]


In [ ]:
np_arr=[1,3,5,7,9,11]
print(np_arr[2])
print(np_arr[1:3])  #print the thirdd elements and slicing from index 1:3

5
[3, 5]


In [ ]:
two_d_array=np.random.randint(0,10,size=(3,3)) #primt the modify array
print(two_d_array)

[[7 8 5]
 [8 8 2]
 [1 0 5]]


In [ ]:
import numpy as np
a=np.array([2,4,6,8])
b=np.array([1,3,5,7])
print(a+b)
print(a*b)

[ 3  7 11 15]
[ 2 12 30 56]


In [ ]:
arr=np.ones((4,3))
print(arr)
r=arr.reshape(3,4)
print(r)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2d numpy array
a=array[1,0:]   #mean
mean=np.mean(a)  #np.mean
print(mean)
print(a)


5.0
[4 5 6]


In [ ]:
array=np.array([10,20,40,40,50,60])   #1D numpy array
a=array>30  #using boolen mask to selected elements greater than 30
print(a)  #print orginal array & modify array
print(array)



[False False  True  True  True  True]
[10 20 40 40 50 60]
