#NUMPY BASICS

## CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [4]:
#Importing numpy library
import numpy as np
#Creating a list named "my_list"
my_list = [1,3,5,7,9]
#Creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)
#Printing the array
print(my_arr)

#Creating a 0-D array
arr_0d = np.array(42)
print(arr_0d)

#Creating a 2-D array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

#Creating a 3-D array
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)

[1 3 5 7 9]
42
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
# Creating array and its attributes
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr)     #Printing the array
print(arr.shape) #Printing the shape of array
print(arr.ndim)   #Dimensions...
print(arr.dtype)  #Type...
print(arr.size)    #Size.....

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)
2
int64
8


# ACCESSING AND MANIPULATING ARRAY ELEMENTS

In [8]:
#Accesing 1-D array elements
my_arr = np.array([2,5,7,9])
print(my_arr[2])

7


In [9]:
#Accesing 2-D array elements
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,2])

5


In [10]:
#Accessing 3-D array elements
my_arr = np.array([[[2,5,7,9],[1,3,5,7]],[[2,5,7,9],[1,3,5,7]]])
print(my_arr[0,1,2])

5


## NEGATIVE INDEXING

In [11]:
#Accesing 2-D array elements with negative indexing
my_arr = np.array([[2,5,7,9],[1,3,5,7]])
print(my_arr[1,-2])

5


## SLICING ARRAYS

### Important concepts while slicing arrays
#### array[start:end]
#### array[start:end:step]

In [12]:
# SLicing a 1-D Numpy Array
arr = np.array([1,3,5,7,9,11,13,15,17,19,21])
print(arr[1:5])  #Slicing
print(arr[1:5:2])  #Slicing with step
print(arr[0:-1])   #Negative

[3 5 7 9]
[3 7]
[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
# Slicing a 2-D Numpy Array
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])

#HOMEWORK: Experiment with slicing on a 3-D Array
#CLASSWORK: Check your whatsapp group

[4 6]
