# NUMPY BASICS

## CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [ ]:
#importing numpy library
import numpy as np
#creating a list
my_list = [1,2,3,4,5]

#changing the list into a 1-D numpy array
my_array = np.array(my_list)
#printing the 1-D numpy array
print(my_array)

#creating a 0-D numpy array
zero_array = np.array(42)
#printing the 0-D numpy array
print(zero_array)

#Instead of creating a list on a separate variable we can directly pass that list to .array()function like this:
my_array = np.array([1,2,3,4,5])
#printing the 1-D numpy array
print(my_array)

#lets create a 2-D array!
two_d_array = np.array([[1,2,3],[4,5,6]])
#printing the 2-D numpy array
print(two_d_array)

#lets create a 3-D array now!
three_d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#printing the 3-D numpy array
print(three_d_array)

[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Lets create an array and see its attributes!
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array)     #Printing the array
print(my_array.ndim)    #Printing the dimension of the array
print(my_array.shape)   #Printing the shape of the array
print(my_array.dtype)   #Printing the type of the array
print(my_array.size)    #Printing the size of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


## ACCESING AND MANIPULATING ARRAY ELEMENTS

In [ ]:
#Lets create a 1-D array and print one of its elements
one_arr = np.array([1,2,3,4,5,6])
print(one_arr[4])

#Lets print using negative indexing
print(one_arr[-3])

5
4


In [ ]:
#Lets do for a 2-D array
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr[1,2])

6


In [ ]:
#Lets move to a 3-D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])

12


## SLICING ARRAYS

### Some Important Slicing Concepts
array[start:end]

araay[start:end:steps]

In [ ]:
#Slicing array from 0th index to 8th index
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[0:8])

[1 2 3 4 5 6 7 8]


In [ ]:
#Slicing with steps
my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])

[1 3 5 7 9]


In [ ]:
#SLICING on a 2-D array
my_two_d = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])

[10 11 12 13 14 15]


In [ ]:
#HOMEWORK: Experiment with slicing on a 3-D Array
#CLASSWORK1: Check your whatsapp group
#CLASSWORK2: Check Numpy documentation to learn more about Numpy and W3 School for content regarding Numpy!

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])